---
title: "ECSAS observation summary"
author: "Dave Fifield"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: true
    number_sections: true
editor_options: 
  chunk_output_type: console
---


```{r get_data, include=FALSE}
source(here::here("R/analysis_settings.R"), echo = FALSE)
the.data <- readRDS(the.data.file)
```


# List of multi-species groups

The following multi-species groups are used in the summary table below.

```{r single_species_groups, echo=FALSE}
library(htmltools)

# idx <- lapply(spec.grps, length) %>% unlist() == 1
# the.species <- names(spec.grps)[idx]
# 
# No need to do these here since they will be covered below when we do all
# species in ECSAS.
# 
# single.species.html <- htmltools::tags$ul(
#       # List items with more indentation
#       lapply(the.species, function(item) {
#         htmltools::tags$li(item)  # Add each item under the group with more indentation
#       })
#     )
# 
# # Combine all lists into a single HTML page
# html_page <- htmltools::tags$html(
#   htmltools::tags$head(),
#   htmltools::tags$body(
#     htmltools::tags$h2("Single species groups"),
#     htmltools::tags$div(single.species.html)  # Add all groups to the body
#   )
# )
#   
# # Return the HTML content as a browsable object
# htmltools::browsable(html_page)

# Do species groups of interest - get multi-species groups
idx <- lapply(spec.grps, length) %>% unlist() != 1
generate_html_species_list(spec.grps[idx])
```


# Summary table for species/groups of interest
```{r grp, echo=FALSE}
# Deal with Sbrds and Wbrds first
sbrds.summ <- the.data$distdata %>%
  rename(Count = size) %>% 
  filter(Seabird == -1) %>% 
  summarise(`4_letter_code` = "Sbrd",
            Seabird = TRUE,
            Waterbird = NA,
            Num_Obs = n(),
            Num_watch = length(unique(WatchID)),
            Total_Count = sum(Count, na.rm = TRUE)) %>%
  mutate(English = "All Seabirds") %>% 
  relocate(English)

wbrds.summ <- the.data$distdata %>%
  rename(Count = size) %>% 
  filter(Waterbird == -1) %>% 
  summarise(`4_letter_code` = "Wbrd",
            Seabird = NA,
            Waterbird = TRUE,
            Num_Obs = n(),
            Num_watch = length(unique(WatchID)),
            Total_Count = sum(Count, na.rm = TRUE)) %>%
  mutate(English = "All Waterbirds") %>% 
  relocate(English)

# Now do the multi-species spec.grps
othr.grps.summ <- the.data$distdata %>%
  rename(Count = size) %>% 
  filter(!is.na(spec.grp) & spec.grp %in% names(spec.grps[idx])) %>% 
  group_by(spec.grp) %>% 
  summarise(`4_letter_code` = unique(spec.grp),
            Seabird = if (unique(Seabird) == -1) TRUE else FALSE,
            Waterbird = if (unique(Waterbird) == -1) TRUE else FALSE,
            Num_Obs = n(),
            Num_watch = length(unique(WatchID)),
            Total_Count = sum(Count, na.rm = TRUE)) %>% 
  mutate(English = unlist(spec.grps.names[othr.grps.summ$spec.grp])) %>% 
  select(-spec.grp) %>% 
  relocate(English)

rbind(sbrds.summ, wbrds.summ, othr.grps.summ) %>% 
  arrange(desc(Total_Count)) %>% 
  knitr::kable("html") %>%
  kableExtra::kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "responsive"),
    full_width = T
  )
```


# Summary all species by species name

Summarize observations by ECSAS taxa entry.

```{r summ_spec, echo = FALSE}
the.data$distdata %>%
  rename(Count = size) %>% 
  group_by(English) %>%
  summarise(`4_letter_code` = unique(Alpha),
            Seabird = if (unique(Seabird) == -1) TRUE else FALSE,
            Waterbird = if (unique(Waterbird) == -1) TRUE else FALSE,
            Num_Obs = n(),
            Num_watch = length(unique(WatchID)),
            Total_Count = sum(Count, na.rm = TRUE)) %>%
  rbind(sbrds.summ, wbrds.summ, othr.grps.summ) %>%
  arrange(desc(Total_Count)) %>% 
  knitr::kable("html") %>%
  kableExtra::kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "responsive"),
    full_width = TRUE
  )
```
